/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class Todo_Encriptador */

#ifndef _Included_Todo_Encriptador
#define _Included_Todo_Encriptador
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Todo_Encriptador
 * Method:    encriptarROT47
 * Signature: (C)C
 */
JNIEXPORT jchar JNICALL Java_Todo_Encriptador_encriptarROT47
  (JNIEnv *, jobject, jchar);

/*
 * Class:     Todo_Encriptador
 * Method:    generarChar
 * Signature: (I)C
 */
JNIEXPORT jchar JNICALL Java_Todo_Encriptador_generarChar
  (JNIEnv *, jobject, jint);

/*
 * Class:     Todo_Encriptador
 * Method:    compararCadenas
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_Todo_Encriptador_compararCadenas
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
