/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Encriptador */

#ifndef _Included_Encriptador
#define _Included_Encriptador
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Encriptador
 * Method:    encriptar
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_Encriptador_encriptar
  (JNIEnv *, jobject, jstring);

/*
 * Class:     Encriptador
 * Method:    desencriptar
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_Encriptador_desencriptar
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
